PracticeProject/mysite/article/urls.py
from django.conf.urls import url
from . import views,list_views

urlpatterns = [
    url(r'^article-column/$', views.article_column,name="article_column"),
    url(r'^rename-column/$', views.rename_article_column,name="rename_article_column"),
    url(r'^del-column/$', views.del_article_column,name="del_article_column"),
    url(r'^article-post/$', views.article_post,name="article_post"),
    url(r'^article-list/$', views.article_list,name="article_list"),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail,name="article_detail"),
    url(r'^del-article/$', views.del_article, name="del_article"),
    url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    url(r'^list-article-titles/$', list_views.article_titles, name="list_article_titles"),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    url(r'^like-articles/$', list_views.like_article, name="like_article"),
]

PracticeProject/mysite/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.blog_title, name="blog_title"),
    url(r"(?P<article_id>\d)", views.blog_article, name="blog_detail"),
]

PracticeProject/mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include("blog.urls", namespace="blog", app_name="blog")),
    url(r'^account/', include("account.urls", namespace="account", app_name="account")),
    # url(r'^pwd_reset/', include("password_reset.urls", namespace="pwd_reset", app_name="pwd_reset")),
    url(r'', include("password_reset.urls")),
    url(r'^article/', include('article.urls',namespace='article',app_name='article')),
    url(r'^home/', TemplateView.as_view(template_name="home.html"),name='home'),
]

PracticeProject/mysite/article/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone
from django.core.urlresolvers import reverse
from slugify import slugify
# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(to=User, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column

class ArticlePost(models.Model):
    author = models.ForeignKey(to=User, related_name='article')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn,related_name='article_column')
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now())
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(to=User, related_name="articles_like", blank=True)

    class Meta:
        ordering = ("title",)
        index_together = (('id','slug'))  # 对这两个字段建立索引

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # 重写save方法,使用awesome slugify而不是django自带的slugify,以支持中文
        self.slug = slugify(self.title)
        super(ArticlePost,self).save(*args, **kwargs)

    def get_absolute_url(self):
        '''
        获取对象的url
        :return:
        '''
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        return reverse("article:list_article_detail", args=[self.id, self.slug])

PracticeProject/mysite/article/forms.py
from django import forms
from .models import ArticleColumn,ArticlePost

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title", "body")

PracticeProject/mysite/article/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import HttpResponse

from .models import ArticleColumn,ArticlePost
from .forms import ArticleColumnForm,ArticlePostForm

from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

# Create your views here.

@login_required(login_url='/account/login/')
@csrf_exempt # 解决csrf问题
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {'columns': columns, 'column_form': column_form})
    if request.method == "POST":
        column_name = request.POST.get('column')
        columns = ArticleColumn.objects.filter(user_id = request.user.id,column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")

@login_required(login_url='/account/login/')
@require_POST   # 保证视图函数只接受POST请求
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST.get('column_name')
    column_id = request.POST.get('column_id')
    print(column_id,column_name)
    try:
        line = ArticleColumn.objects.get(id=column_id)
        print(line.pk)
        line.column = column_name
        line.save()
        return HttpResponse('1')
    except Exception as e:
        print(e)
        return HttpResponse('0')


@login_required(login_url='/account/login/')
@require_POST   # 保证视图函数只接受POST请求
@csrf_exempt
def del_article_column(request):
    column_id = request.POST.get('column_id')
    try:
        line = ArticleColumn.objects.get(pk=column_id)
        line.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')

@login_required(login_url='/account/login/')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form  = ArticlePostForm(data = request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST.get('column_id'))
                new_article.save()
                return HttpResponse("1")
            except Exception as e:
                print(e)
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        return render(request, 'article/column/article_post.html',{
            'article_post_form': article_post_form,
            'article_columns': article_columns
        })

@login_required(login_url='/account/login/')
@csrf_exempt
def article_list(request):
    article_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(article_list, 2)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, 'article/column/article_list.html', {'articles': articles,'page': current_page})

@login_required(login_url='/account/login/')
def article_detail(request,id,slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, 'article/column/article_detail.html', dict(article=article))

@login_required(login_url='/account/login/')
@csrf_exempt
@require_POST
def del_article(request):
    if request.method == "POST":
        article_id = request.POST.get("article_id")
        try:
            article = ArticlePost.objects.get(pk=article_id)
            article.delete()
            return HttpResponse('1')
        except Exception as e:
            print(e)
            return HttpResponse('0')


@login_required(login_url='/account/login/')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        return render(request, "article/column/redit_article.html",{
            "article": article,
            "article_columns": article_columns,
            "this_article_form": this_article_form,
            "this_article_column": this_article_column,
        })
    elif request.method == "POST":
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST.get("column_id"))
            redit_article.title = request.POST.get('title')
            redit_article.body = request.POST.get('body')
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")

PracticeProject/mysite/templates/article/column/article_column.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
    <div>
        <p class="text-right">
            <button class="btn btn-primary" id="add_column" onclick="add_column()">add column</button>
        </p>
        <table class="table table-hover">
            <tr>
                <td>序号</td>
                <td>栏目名</td>
                <td>操作</td>
            </tr>
            {% for column in columns %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ column.column }}</td>
                    <td>
                        <a name="edit" href="javascript:" onclick="edit_column(this, {{ column.id }})"><span
                                class="glyphicon glyphicon-pencil"></span></a>
                        <a name="delete" href="javascript:" onclick="del_column(this, {{ column.id }})"><span
                                class="glyphicon glyphicon-trash" style="margin-left: 20px;"></span></a>
                    </td>
                </tr>
            {% empty %}
                <p>还没有设置栏目,太懒了</p>
            {% endfor %}
        </table>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript">
        function add_column() {
            var index = layer.open({
                type: 1,
                skin: 'layui-layer-rim',
                area: ['400px', '200px'],
                title: "新增栏目",
                content: '<div class="text-center" style="margin-top: 20px"><p>请输入新的栏目名</p><input id="id_column" type="text"/><p></p></div>',
                btn: ["确认", "取消"],
                yes: function (index, layero) {
                    column_name = $('#id_column').val();
                    // alert(column_name);
                    $.ajax({
                        url: '{% url "article:article_column" %}',
                        type: 'POST',
                        data: {"column": column_name},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("good");
                            } else {
                                layer.msg("此栏目已有,请更换名称")
                            }
                        }
                    });
                },
                btn2: function (index, layero) {
                    layer.close()
                }
            })
        }

        function edit_column(the, column_id) {
            var name = $(the).parents("tr").children("td").eq(1).text();
            var index = layer.open({
                type: 1,
                skin: 'layui-layer-rim',
                area: ["400px", "200px"],
                title: "编辑栏目",
                content: '<div class="text-center" style="margin-top: 20px"><p>请编辑的栏目的名称</p><p><input type="tesx" id="new_name" value="' + name + '"/></p></div>',
                btn: ['确认', '取消'],
                yes: function (index, layero) {
                    new_name = $("#new_name").val();
                    console.log(column_id, new_name);
                    $.ajax({
                        url: "{% url 'article:rename_article_column' %}",
                        type: "POST",
                        data: {"column_id": column_id, "column_name": new_name},
                        success: function (e) {
                            if (e == '1') {
                                parent.location.reload();
                                layer.msg("good");
                            } else {
                                layer.msg("新的名称没有保存,修改失败")
                            }
                        }
                    });
                },
            })
        }

        function del_column(the, column_id) {
            var name = $(the).parent("tr").children("td").eq(1).text();
            layer.open(
                {
                    type: 1,
                    skin: 'layui-layer-rim',
                    area: ["400px", "200px"],
                    title: "删除栏目",
                    content: "<div class='text-center' style='margin-top: 20px'><p>是否确认删除" + name + "</p></div>",
                    btn: ["确认", "取消"],
                    yes: function () {
                        $.ajax({
                            url: "{% url 'article:del_article_column' %}",
                            type: "POST",
                            data: {'column_id': column_id},
                            success: function (e) {
                                if (e == '1') {
                                    parent.location.reload();
                                    layer.msg('已删除');
                                } else {
                                    layer.msg("删除失败");
                                }
                            },
                        })
                    },
                }
            )
        }
    </script>
{% endblock %}

PracticeProject/mysite/templates/article/column/article_detail.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}article detail{% endblock %}

{% block content %}
    <header>
        <h1 class="text-capitalize text-center">{{ article.title }}</h1>
        <p class="text-right">作者:{{ user.username }}</p>
    </header>
     <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.min.css' %}">
    <div id="editormd-view">
        <textarea id="append_test" style="display: none">{{ article.body }}</textarea>
    </div>
    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.min.js' %}"></script>
    <script type="text/javascript">
    $(function(){
        editormd.markdownToHTML('editormd-view',{
            htmlDecode      : "style,script,iframe",  // you can filter tags decode
            emoji           : true,
            taskList        : true,
            tex             : true,  // 默认不解析
            flowChart       : true,  // 默认不解析
            sequenceDiagram : true,  // 默认不解析
        })
    })
    </script>
{% endblock %}

PracticeProject/mysite/templates/article/column/article_list.html
{% extends 'article/base.html' %}

{% load staticfiles %}

{% block title %}article list{% endblock %}

{% block content %}
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>标题</td>
            <td>栏目</td>
            <td>操作</td>
        </tr>
        {% for article in articles %}
            <tr id="{{ article.id }}">
                <td>{{ forloop.counter }}</td>
                <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
                <td>{{ article.column }}</td>
                <td>
                    <a name="edit" href="{% url 'article:redit_article' article.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a name='delete' href="javascript:" onclick="del_article(this,{{ article.id }})">
                        <span class="glyphicon glyphicon-trash" style="margin-left: 10px"></span>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>
    {% include 'paginator.html' %}

    <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <Script type="text/javascript">
    function del_article(the, article_id){
        var article_name = $(the).parents('tr').children('td').eq(1).text();
        layer.open({
            type: 1,
            skin: 'layui-layer-rim',
            area: ["400px", "200px"],
            title: '删除文章',
            content: "<div class='text-center' style='margin-top: 20px'><p>是否删除"+article_name+"</p></div>",
            btn: ['确认','取消'],
            yes: function(){
                $.ajax({
                    url: '{% url "article:del_article" %}',
                    type: 'post',
                    data: {"article_id": article_id},
                    success: function(e){
                        if(e == '1'){
                            parent.location.reload();
                            layer.msg("has been deleted.");
                        }else{
                            layer.msg("删除失败");
                        }
                    }
                })
            }
        })
    }
    </Script>
{% endblock %}

PracticeProject/mysite/templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.min.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">

    <div class="form-horizontal" action="." method="post">
        {% csrf_token %}
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>标题:</span></div>
            <div class="col-md-10 text-left">{{ article_post_form.title }}</div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right">栏目:</div>
            <div class="col-md-10 text-left">
                <select name="" id="which_column">
                    {% for column in article_columns %}
                        <option value="{{ column.id }}">{{ column.column }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>内容:</span></div>
            <!--
        <div class="col-md-10 text-left">{{ article_post_form.body }}</div>
        -->
            <div id='editormd' class="col-md-10 text-left">
                <textarea style='display: none' id="id_body"></textarea>
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="publish_article()">
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript">
        function publish_article() {
            var title = $('#id_title').val();
            var column_id = $('#which_column').val();
            var body = $('#id_body').val();
            $.ajax({
                url: "{% url 'article:article_post' %}",
                method: 'POST',
                data: {'title': title, 'body': body, 'column_id': column_id},
                success: function (e) {
                    if (e == '1') {
                        layer.msg("successful");
                        location.href = "{% url 'article:article_list' %}";
                    } else if (e == '2') {
                        layer.msg("sorry.")
                    } else {
                        layer.msg("项目名称必须填写,不能为空.")
                    }
                },
            });
        }
    </script>
    <script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            var editor = editormd("editormd", {
                width: "100%",
                height: 640,
                syncScrolling: "single",
                path: "{% static 'editor/lib/' %}"
            });
        });
    </script>

{% endblock %}

PracticeProject/mysite/templates/article/column/redit_article.html
{% extends "article/base.html" %}
{% load staticfiles %}

{% block title %}article column{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.min.css' %}">
    <div class="container">
        <div class="col-md-10">
            <div style="margin-left: 10px;">
                <form class="form-horizontal" action="." method="post">
                    {% csrf_token %}
                    <div class="row" style="margin-top:10px;">
                        <div class="col-md-2 text-right"><span>标题:</span></div>
                        <div class="col-md-10 text-left"><span>{{ this_article_form.title }}</span></div>
                    </div>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-2 text-right"><span>栏目:</span></div>
                        <div class="col-md-10 text-left">
                            <select name="" id="which_column">
                                {% for column in article_columns %}
                                    {% if column == this_article_column.column %}
                                        <option value="{{ column.id }}" selected="selected">{{ column.column }}</option>
                                    {% else %}
                                        <option value="{{ column.id }}">{{ column.column }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-2 text-right"><span>内容:</span></div>
                        <div id="editormd" class="col-md-10 text-left">
                            <!--{{ this_article_form.body }}-->
                            <textarea style="display: none" id="id_body">{{ article.body }}</textarea>
                        </div>
                    </div>
                    <div class="row">
                        <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="redit_article()">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript">
    $(function(){
        var editor = editormd("editormd",{
            width: "100%",
            height: 640,
            path: "{% static 'editor/lib/' %}"
        })
    });

    function redit_article(){
        var title = $("#id_title").val();
        var column_id = $("#which_column").val();
        var body = $("#id_body").val();
        $.ajax({
            url: "{% url 'article:redit_article' article.id %}",
            type: "post",
            data: {
                "title": title,
                "column_id": column_id,
                "body": body
            },
            success: function(e){
                if(e == '1'){
                    layer.msg("successful");
                    location.href = "{% url 'article:article_list' %}"
                }else{
                    layer.msg("sorry.");
                }
            }
        })
    }
    </script>
{% endblock %}