PracticeProject/mysite/account/urls.py
from django.conf.urls import url
from . import views

from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns =[
    # url(r'^login/$',views.user_login, name="user_login"),
    url(r'^login/$',auth_views.login, name="user_login"),
    url(r'^new-login/$',auth_views.login, {"template_name": "account/login.html"}),
    url(r'^logout/$',auth_views.logout, {"template_name" : "account/logout.html"},name="user_logout"),
    url(r'^register/$',views.register,name="user_register"),
    url(r'^password-change/$',
        auth_views.password_change,
        {"post_change_redirect": "/account/password-change-done"},
        name="password_change"),
    url(r'^password-change-done/$',auth_views.password_change_done,name="password_change_done"),
    url(r'^password-reset/$',auth_views.password_reset,
        {"template_name": 'account/password_reset_form.html',
         "email_template_name": 'account/password_reset_email.html',
         "subject_template_name": 'account/password_reset_subject.txt',
         "post_reset_redirect": '/account/password-reset-done/'},
        name="password_reset"),
    url(r'^password-reset-done/$',auth_views.password_reset_done,
        {"template_name": 'account/password_reset_done.html'},
        name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',auth_views.password_reset_confirm,
        {"template_name": 'account/password_reset_confirm.html',
         'post_reset_redirect': '/account/password-reset-complete/'},
        name="password_reset_confirm"),
    url(r'^password-reset-complete/$',auth_views.password_reset_complete,
        {"template_name": 'account/password_reset_complete.html'},
        name="password_reset_complete"),
    url(r'^my-information/$',views.myself,name="my-information"),
    url(r'^edit-my-information/$',views.myself_edit,name="edit-my-information"),
    url(r'my-image/$',views.my_image,name="my_image")
]

PracticeProject/mysite/article/urls.py
from django.conf.urls import url
from . import views,list_views

urlpatterns = [
    url(r'^article-column/$', views.article_column,name="article_column"),
    url(r'^rename-column/$', views.rename_article_column,name="rename_article_column"),
    url(r'^del-column/$', views.del_article_column,name="del_article_column"),
    url(r'^article-post/$', views.article_post,name="article_post"),
    url(r'^article-list/$', views.article_list,name="article_list"),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail,name="article_detail"),
    url(r'^del-article/$', views.del_article, name="del_article"),
    url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    url(r'^list-article-titles/$', list_views.article_titles, name="list_article_titles"),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    url(r'^like-articles/$', list_views.like_article, name="like_article"),
]

PracticeProject/mysite/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.blog_title, name="blog_title"),
    url(r"(?P<article_id>\d)", views.blog_article, name="blog_detail"),
]

PracticeProject/mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include("blog.urls", namespace="blog", app_name="blog")),
    url(r'^account/', include("account.urls", namespace="account", app_name="account")),
    # url(r'^pwd_reset/', include("password_reset.urls", namespace="pwd_reset", app_name="pwd_reset")),
    url(r'', include("password_reset.urls")),
    url(r'^article/', include('article.urls',namespace='article',app_name='article')),
    url(r'^home/', TemplateView.as_view(template_name="home.html"),name='home'),
]

PracticeProject/mysite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, inital-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bs/css/bootstrap.min.css' %}">
</head>
<body>
{% include "header.html" %}
<div class="container">
    {% block content %}{% endblock %}
</div>
{% include "footer.html" %}
{% block javascripts %}{% endblock %}
</body>
</html>

PracticeProject/mysite/templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copyright www.fbo.com</p>
</div>

PracticeProject/mysite/templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="nav navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href=""><img src="{% static 'images/pingan.png' %}" width="100px" height="35px"
                                                 alt=""></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url "blog:blog_title" %}">BLOG</a></li>
                <li><a href="{% url "article:list_article_titles" %}">Article</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px">
                {% if user.is_authenticated %}
                    <!--<li><a href="">{{ user.username }}</a></li>-->
                    <li>
                        <div class="dropdown" style="margin-top:8px;">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu"
                                    data-toggle="dropdown">
                                {{ user.username }} <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                                <li><a href="{% url 'account:my-information' %}">个人信息</a></li>
                            </ul>
                        </div>
                    </li>

                    <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'account:user_login' %}">Login</a></li>
                    <li><a href="{% url 'account:user_register' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'bs/js/bootstrap.min.js' %}"></script>

PracticeProject/mysite/templates/home.html
{% extends "base.html" %}
{% block title %}Home page{% endblock %}
{% block content %}
    <div class="text-center">
    <h1>WELCOM YOU</h1>
    <h3>Life is short, You need Python</h3>
    <h2>Django makes it easier to build better web apps more quickly and with less code.</h2>
    {% load staticfiles %}
        <img src="{% static 'images/xiong.jpg' %}"
    </div>
{% endblock %}

PracticeProject/mysite/templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>